version: '3'

services:
  npx-api:
    build: .
    ports:
      - "10000-10020:10000-10020"
    environment:
      - NODE_OPTIONS=--no-warnings
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge